x-common-env: &common-env
  PYTHONPATH: "/app"

services:
  app:
    profiles: ["dev", "prod"]
    container_name: medblip_streamlit_app
    build:
      context: ..
      dockerfile: docker/Dockerfile
    env_file:
      - ../.env
    user: root
    ports:
      - "8501:8501"
    volumes:
      - ..:/app
      - ../model:/app/model
    environment:
      <<: *common-env
    mem_limit: 4g
    cpus: 2
    restart: unless-stopped

