x-common-env: &common-env
  PYTHONPATH: "/app"
  # LLM Configuration - can be overridden in .env
  OPENAI_API_KEY: ${OPENAI_API_KEY:-}
  OPENAI_API_BASE: ${OPENAI_API_BASE:-}
  OPENAI_MODEL: ${OPENAI_MODEL:-gpt-4o-mini}
  # Langfuse Observability - can be overridden in .env
  LANGFUSE_ENABLED: ${LANGFUSE_ENABLED:-false}
  LANGFUSE_PUBLIC_KEY: ${LANGFUSE_PUBLIC_KEY:-}
  LANGFUSE_SECRET_KEY: ${LANGFUSE_SECRET_KEY:-}
  LANGFUSE_HOST: ${LANGFUSE_HOST:-}

services:
  app:
    profiles: ["prod"]
    container_name: medblip_streamlit_app
    build:
      context: ..
      dockerfile: docker/Dockerfile
    env_file:
      - ../.env
    user: root
    ports:
      - "8501:8501"
    volumes:
      - ../model:/app/model
    environment:
      <<: *common-env
    mem_limit: 4g
    cpus: 2
    restart: unless-stopped
